package info.alihabibi.model.ui_model.channel

import androidx.annotation.DrawableRes
import info.alihabibi.designsystem.R

enum class ChannelIconOptionUiModel(
    @get:DrawableRes val iconResId: Int
) {
    FOOD(R.drawable.category_ic_food),
    SHOPPING(R.drawable.category_ic_shopping),
    HAVING_FUN(R.drawable.category_ic_having_fun),
    HOME(R.drawable.category_ic_home),
    CAR(R.drawable.category_ic_car),
    SALARY(R.drawable.category_ic_salary),
    INCOME(R.drawable.category_ic_income),
    OTHERS(R.drawable.category_ic_others),
    PROFIT(R.drawable.category_ic_profit),
    SUBSIDY(R.drawable.category_ic_subsidy),
    ACTIVITY(R.drawable.category_ic_activity),
    AI(R.drawable.category_ic_ai),
    AIRPLANE(R.drawable.category_ic_airplane),
    BANK(R.drawable.category_ic_bank),
    BITCOIN(R.drawable.category_ic_bitcoin),
    BOOK(R.drawable.category_ic_book),
    BOX(R.drawable.category_ic_box),
    CARD_SEND(R.drawable.category_ic_card_send),
    COFFEE(R.drawable.category_ic_coffee),
    COIN(R.drawable.category_ic_coin),
    COMPUTER(R.drawable.category_ic_computer),
    EDUCATION(R.drawable.category_ic_education),
    EMOJI_HAPPY(R.drawable.category_ic_emoji_happy),
    GAME(R.drawable.category_ic_game),
    GIFT(R.drawable.category_ic_gift),
    HEART(R.drawable.category_ic_heart),
    HOSPITAL(R.drawable.category_ic_hospital),
    LAMP(R.drawable.category_ic_lamp),
    PEOPLE(R.drawable.category_ic_people),
    PET(R.drawable.category_ic_pet),
    RECEIPT(R.drawable.category_ic_receipt),
    ROUTING(R.drawable.category_ic_routing),

    UNKNOWN(R.drawable.channel_ic_default),

    ANSAR(info.alihabibi.common.R.drawable.ansar),
    BLU_BANK(info.alihabibi.common.R.drawable.blu),
    DEY(info.alihabibi.common.R.drawable.dey),
    EGHTESAD_NOVIN(info.alihabibi.common.R.drawable.eghtesad_novin),
    GARDESHGARI(info.alihabibi.common.R.drawable.gardeshgari),
    GHAVAMIN(info.alihabibi.common.R.drawable.ghavamin),
    HEKMAT_IRANIAN(info.alihabibi.common.R.drawable.hekmat_iranian),
    IRAN_VENEZUELA(info.alihabibi.common.R.drawable.iran_venezuela),
    IRAN_ZAMIN(info.alihabibi.common.R.drawable.iran_zamin),
    KARAFARIN(info.alihabibi.common.R.drawable.karafarin),
    KESHAVARZI(info.alihabibi.common.R.drawable.keshavarzi),
    KHAVARMIANEH(info.alihabibi.common.R.drawable.khavar_mianeh),
    MASKAN(info.alihabibi.common.R.drawable.maskan),
    MEHR_IRAN(info.alihabibi.common.R.drawable.mehr_iran),
    MELAL(info.alihabibi.common.R.drawable.mellal),
    MELLAT(info.alihabibi.common.R.drawable.mellat),
    MELLI(info.alihabibi.common.R.drawable.melli),
    PARSIAN(info.alihabibi.common.R.drawable.parsian),
    PASARGAD(info.alihabibi.common.R.drawable.pasargad),
    POST_BANK(info.alihabibi.common.R.drawable.post),
    REFAH(info.alihabibi.common.R.drawable.refah),
    RESALAT(info.alihabibi.common.R.drawable.resalat),
    SADERAT(info.alihabibi.common.R.drawable.saderat),
    SAMAN(info.alihabibi.common.R.drawable.saman),
    SANAT_O_MADAN(info.alihabibi.common.R.drawable.sanat_madan),
    SARMAYEH(info.alihabibi.common.R.drawable.sarmayeh),
    SEPAH(info.alihabibi.common.R.drawable.sepah),
    SHAHR(info.alihabibi.common.R.drawable.shahr),
    SINA(info.alihabibi.common.R.drawable.sina),
    TEJARAT(info.alihabibi.common.R.drawable.tejarat),
    TOSSE_SADERAT(info.alihabibi.common.R.drawable.tosee_saderat),
    TOSSE_TAAVON(info.alihabibi.common.R.drawable.tosee_taavon),
    WEPOD(info.alihabibi.common.R.drawable.wepod);
}